/*
 * This file was automatically generated by EvoSuite
 * Sat Aug 29 12:49:41 GMT 2026
 */

package org.apache.avro.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import org.apache.avro.util.Utf8;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true)
public class Utf8_ESTest extends Utf8_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    int int0 = Utf8.compareSequences("", utf8_0);
    assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test01() throws Throwable {
    Utf8 utf8_0 = new Utf8("-5.6D8[[?%/nW,u#G", 2053);
    int int0 = Utf8.compareSequences("EE)_6", utf8_0);
    assertEquals(24, int0);
  }

  @Test(timeout = 4000)
  public void test02() throws Throwable {
    Utf8 utf8_0 = new Utf8(")T~fT,{8>,2z[K%", (-1642));
    utf8_0.hashCode();
  }

  @Test(timeout = 4000)
  public void test03() throws Throwable {
    Utf8 utf8_0 = new Utf8("~]gA{&`{wfq|=");
    Utf8 utf8_1 = new Utf8("[2,_M#(bM1#");
    Utf8 utf8_2 = utf8_0.set(utf8_1);
    utf8_2.hashCode();
    assertEquals(11, utf8_0.getByteLength());
    assertTrue(utf8_0.equals((Object) utf8_1));
  }

  @Test(timeout = 4000)
  public void test04() throws Throwable {
    Utf8 utf8_0 = new Utf8(")T~fT,{8>,2z[K%", (-1642));
    Utf8 utf8_1 = utf8_0.setByteLength(7);
    utf8_1.hashCode();
    assertEquals(7, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test05() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    byte[] byteArray0 = new byte[6];
    Utf8 utf8_1 = new Utf8(byteArray0);
    boolean boolean0 = utf8_1.equals(utf8_0);
    assertFalse(utf8_0.equals((Object) utf8_1));
    assertEquals(6, utf8_1.getByteLength());
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    Utf8 utf8_1 = new Utf8(utf8_0);
    Utf8 utf8_2 = utf8_1.set(utf8_0);
    assertSame(utf8_2, utf8_1);
  }

  @Test(timeout = 4000)
  public void test07() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.util.Utf8", (-2156));
    // Undeclared exception!
    try {
      utf8_0.set(utf8_0);
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
    }
  }

  @Test(timeout = 4000)
  public void test08() throws Throwable {
    byte[] byteArray0 = new byte[3];
    Utf8 utf8_0 = new Utf8(byteArray0);
    CharSequence charSequence0 = utf8_0.subSequence(0, 0);
    assertEquals("", charSequence0);
    assertEquals(3, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test09() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.string.maxLength");
    utf8_0.set("");
    assertEquals(0, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test10() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    int int0 = utf8_0.length();
    assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test11() throws Throwable {
    Utf8 utf8_0 = new Utf8("L\"#9SOMs", (-1517));
    int int0 = utf8_0.length();
    assertEquals(8, int0);
    assertEquals((-1517), utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test12() throws Throwable {
    byte[] byteArray0 = Utf8.getBytesFor("");
    assertEquals(0, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test13() throws Throwable {
    byte[] byteArray0 = Utf8.getBytesFor("yH0hqplqP}+&+374");
    Utf8 utf8_0 = new Utf8(byteArray0);
    utf8_0.getBytes();
    assertEquals(16, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test14() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    int int0 = utf8_0.getByteLength();
    assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test15() throws Throwable {
    Utf8 utf8_0 = new Utf8(")T~fT,{8>,2z[K%", (-1642));
    int int0 = utf8_0.getByteLength();
    assertEquals((-1642), int0);
  }

  @Test(timeout = 4000)
  public void test16() throws Throwable {
    Utf8 utf8_0 = new Utf8(")T~fT,{8>,2z[K%", (-1642));
    utf8_0.setByteLength(7);
    Utf8 utf8_1 = new Utf8("", 0);
    int int0 = utf8_0.compareTo(utf8_1);
    assertEquals(7, utf8_0.getByteLength());
    assertEquals(7, int0);
  }

  @Test(timeout = 4000)
  public void test17() throws Throwable {
    Utf8 utf8_0 = new Utf8("Buffer size %,d (bytes) exceeds maximum allowed size %,d.");
    Utf8 utf8_1 = new Utf8("~AX+[o&CbDBU");
    int int0 = utf8_0.compareTo(utf8_1);
    assertEquals(12, utf8_1.getByteLength());
    assertEquals((-60), int0);
  }

  @Test(timeout = 4000)
  public void test18() throws Throwable {
    Utf8 utf8_0 = new Utf8(")T~fT,{8>,2z[K%", (-1642));
    utf8_0.setByteLength(33);
    utf8_0.charAt(7);
    assertEquals(33, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test19() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.AvroRuntimeException", 1);
    char char0 = utf8_0.charAt(0);
    assertEquals('o', char0);
    assertEquals(1, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test20() throws Throwable {
    byte[] byteArray0 = new byte[3];
    Utf8 utf8_0 = new Utf8(byteArray0);
    // Undeclared exception!
    try {
      utf8_0.writeExternal((ObjectOutput) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test21() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    // Undeclared exception!
    try {
      utf8_0.setByteLength((-1459));
      fail("Expecting exception: RuntimeException");

    } catch (RuntimeException e) {
      //
      // Malformed data. Length is negative: -1459
      //
      verifyException("org.apache.avro.SystemLimitException", e);
    }
  }

  @Test(timeout = 4000)
  public void test22() throws Throwable {
    Utf8 utf8_0 = new Utf8("et");
    // Undeclared exception!
    try {
      utf8_0.set((Utf8) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test23() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.io.BinaryDecoder", 635);
    Utf8 utf8_1 = new Utf8("", 635);
    // Undeclared exception!
    try {
      utf8_0.set(utf8_1);
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
    }
  }

  @Test(timeout = 4000)
  public void test24() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    // Undeclared exception!
    try {
      utf8_0.set((String) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test25() throws Throwable {
    // Undeclared exception!
    try {
      Utf8.getBytesFor((String) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test26() throws Throwable {
    Utf8 utf8_0 = new Utf8("K^t=N\"", 7);
    // Undeclared exception!
    try {
      utf8_0.compareTo((Utf8) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test27() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    Utf8 utf8_1 = new Utf8(")8NY`I", (-117));
    // Undeclared exception!
    try {
      utf8_0.compareTo(utf8_1);
      fail("Expecting exception: IllegalArgumentException");

    } catch (IllegalArgumentException e) {
      //
      // fromIndex(0) > toIndex(-117)
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test28() throws Throwable {
    Utf8 utf8_0 = new Utf8(";4E5Z&");
    Utf8 utf8_1 = new Utf8("", 7);
    // Undeclared exception!
    try {
      utf8_0.compareTo(utf8_1);
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
      //
      // Array index out of range: 7
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test29() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    Utf8 utf8_1 = new Utf8("tb[R7w:It{rHxH$6^={", (-672));
    // Undeclared exception!
    try {
      Utf8.compareSequences(utf8_1, utf8_0);
      fail("Expecting exception: IllegalArgumentException");

    } catch (IllegalArgumentException e) {
      //
      // fromIndex(0) > toIndex(-672)
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test30() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    Utf8 utf8_1 = new Utf8("NVq<n`W'1w]~KY", 25);
    // Undeclared exception!
    try {
      Utf8.compareSequences(utf8_0, utf8_1);
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
      //
      // Array index out of range: 25
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test31() throws Throwable {
    Utf8 utf8_0 = null;
    try {
      utf8_0 = new Utf8((byte[]) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test32() throws Throwable {
    Utf8 utf8_0 = null;
    try {
      utf8_0 = new Utf8((Utf8) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test33() throws Throwable {
    Utf8 utf8_0 = new Utf8("GH5<Hr[duD[:e[}atgp", (-1));
    Utf8 utf8_1 = null;
    try {
      utf8_1 = new Utf8(utf8_0);
      fail("Expecting exception: NegativeArraySizeException");

    } catch (NegativeArraySizeException e) {
      //
      // -1
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test34() throws Throwable {
    Utf8 utf8_0 = null;
    try {
      utf8_0 = new Utf8((String) null, 4);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test35() throws Throwable {
    Utf8 utf8_0 = null;
    try {
      utf8_0 = new Utf8((String) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test36() throws Throwable {
    byte[] byteArray0 = Utf8.getBytesFor("yH0hqplqP}+&+374");
    Utf8 utf8_0 = new Utf8(byteArray0);
    String string0 = utf8_0.toString();
    assertEquals("yH0hqplqP}+&+374", string0);
  }

  @Test(timeout = 4000)
  public void test37() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    String string0 = utf8_0.toString();
    assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test38() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.bytes.maxLength", (-27));
    String string0 = utf8_0.toString();
    assertEquals("org.apache.avro.limits.bytes.maxLength", string0);
    assertEquals((-27), utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test39() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    // Undeclared exception!
    try {
      utf8_0.charAt((-1));
      fail("Expecting exception: StringIndexOutOfBoundsException");

    } catch (StringIndexOutOfBoundsException e) {
    }
  }

  @Test(timeout = 4000)
  public void test40() throws Throwable {
    Utf8 utf8_0 = new Utf8("Tl<d");
    int int0 = Utf8.compareSequences(";4E5Z&", utf8_0);
    assertEquals(4, utf8_0.getByteLength());
    assertEquals((-25), int0);
  }

  @Test(timeout = 4000)
  public void test41() throws Throwable {
    int int0 = Utf8.compareSequences("Could not parse property '{}' value '{}'. Using default: {}",
        (CharSequence) null);
    assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test42() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.bytes.maxLength", (-27));
    int int0 = Utf8.compareSequences((CharSequence) null, utf8_0);
    assertEquals((-27), utf8_0.getByteLength());
    assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test43() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    int int0 = Utf8.compareSequences(utf8_0, utf8_0);
    assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test44() throws Throwable {
    Utf8 utf8_0 = new Utf8("Th^(]rt3jTS.");
    utf8_0.hashCode();
    assertEquals(12, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test45() throws Throwable {
    Utf8 utf8_0 = new Utf8("", 31);
    // Undeclared exception!
    try {
      utf8_0.hashCode();
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
      //
      // Index 0 out of bounds for length 0
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test46() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    utf8_0.hashCode();
  }

  @Test(timeout = 4000)
  public void test47() throws Throwable {
    Utf8 utf8_0 = new Utf8("t");
    Utf8 utf8_1 = new Utf8(utf8_0);
    boolean boolean0 = utf8_1.equals(utf8_0);
    assertTrue(boolean0);
    assertEquals(1, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test48() throws Throwable {
    Utf8 utf8_0 = new Utf8("HKS", 16);
    Utf8 utf8_1 = new Utf8(utf8_0);
    // Undeclared exception!
    try {
      utf8_1.equals(utf8_0);
      fail("Expecting exception: ArrayIndexOutOfBoundsException");

    } catch (ArrayIndexOutOfBoundsException e) {
      //
      // Array index out of range: 16
      //
      verifyException("java.util.Arrays", e);
    }
  }

  @Test(timeout = 4000)
  public void test49() throws Throwable {
    Utf8 utf8_0 = new Utf8("R\"");
    Utf8 utf8_1 = new Utf8();
    boolean boolean0 = utf8_1.equals(utf8_0);
    assertEquals(2, utf8_0.getByteLength());
    assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test50() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.string.maxLength");
    boolean boolean0 = utf8_0.equals((Object) null);
    assertFalse(boolean0);
    assertEquals(39, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test51() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.string.maxLength");
    boolean boolean0 = utf8_0.equals(utf8_0);
    assertEquals(39, utf8_0.getByteLength());
    assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test52() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.bytes.maxLength", (-27));
    Utf8 utf8_1 = new Utf8("org.apache.avro.limits.bytes.maxLength", (-27));
    boolean boolean0 = utf8_1.equals(utf8_0);
    assertTrue(boolean0);
    assertEquals((-27), utf8_1.getByteLength());
  }

  @Test(timeout = 4000)
  public void test53() throws Throwable {
    byte[] byteArray0 = Utf8.getBytesFor("yH0hqplqP}+&+374");
    Utf8 utf8_0 = new Utf8(byteArray0);
    int int0 = Utf8.compareSequences("yH0hqplqP}+&+374", utf8_0);
    assertEquals(0, int0);
    assertEquals(16, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test54() throws Throwable {
    Utf8 utf8_0 = new Utf8("");
    Utf8 utf8_1 = utf8_0.setByteLength(112);
    CharSequence charSequence0 = utf8_1.subSequence(2, 4);
    assertEquals(112, utf8_0.getByteLength());
    assertEquals("\u0000\u0000", charSequence0);
  }

  @Test(timeout = 4000)
  public void test55() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    Utf8 utf8_1 = utf8_0.setByteLength((byte) 0);
    assertEquals(0, utf8_1.getByteLength());
  }

  @Test(timeout = 4000)
  public void test56() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    MockPrintStream mockPrintStream0 = new MockPrintStream("6/");
    ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
    utf8_0.writeExternal(objectOutputStream0);
    assertEquals(0, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test57() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    int int0 = utf8_0.compareTo(utf8_0);
    assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test58() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    utf8_0.set("6/");
    assertEquals(2, utf8_0.getByteLength());
  }

  @Test(timeout = 4000)
  public void test59() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    // Undeclared exception!
    try {
      utf8_0.readExternal((ObjectInput) null);
      fail("Expecting exception: NullPointerException");

    } catch (NullPointerException e) {
      //
      // no message in exception (getMessage() returned null)
      //
      verifyException("org.apache.avro.util.Utf8", e);
    }
  }

  @Test(timeout = 4000)
  public void test60() throws Throwable {
    Utf8 utf8_0 = new Utf8();
    byte[] byteArray0 = utf8_0.getBytes();
    assertEquals(0, byteArray0.length);
  }

  @Test(timeout = 4000)
  public void test61() throws Throwable {
    Utf8 utf8_0 = new Utf8("");
    // Undeclared exception!
    try {
      utf8_0.subSequence(2, 4);
      fail("Expecting exception: StringIndexOutOfBoundsException");

    } catch (StringIndexOutOfBoundsException e) {
    }
  }

  @Test(timeout = 4000)
  public void test62() throws Throwable {
    Utf8 utf8_0 = new Utf8("org.apache.avro.limits.string.maxLength");
    int int0 = utf8_0.getByteLength();
    assertEquals(39, int0);
  }
}
