/*
 * This file was automatically generated by EvoSuite
 * Tue Aug 18 15:05:05 GMT 2026
 */

package org.apache.avro;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import org.apache.avro.Conversions;
import org.apache.avro.NameValidator;
import org.apache.avro.ParseContext;
import org.apache.avro.Protocol;
import org.apache.avro.Resolver;
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericData;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Resolver_ESTest extends Resolver_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(schema1, schema0);
      assertFalse(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("UresovedpSchma_995", "UresovedpSchma_995", "UresovedpSchma_995", (List<String>) linkedList0);
      Schema schema1 = Schema.createEnum("UresovedpSchma_995", "UresovedpSchma_995", "UresovedpSchma_995", (List<String>) linkedList0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      GenericData genericData0 = new GenericData();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema1, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"enum\",\"name\":\"UresovedpSchma_995\",\"namespace\":\"UresovedpSchma_995\",\"doc\":\"UresovedpSchma_995\",\"symbols\":[]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createMap(schema0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      Schema schema2 = Schema.createMap(resolver_Action0.writer);
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema1, schema2, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"map\",\"values\":[\"string\"]}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      ParseContext parseContext0 = new ParseContext();
      Schema schema1 = parseContext0.resolve(resolver_Action0.reader);
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(resolver_Action0.writer, schema1);
      assertTrue(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      NameValidator nameValidator0 = mock(NameValidator.class, new ViolatedAssumptionAnswer());
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("UnresolvedSchema_213", "UnresolvedSchema_213");
      GenericData genericData0 = new GenericData();
      Schema schema1 = parseContext0.find("avro.java.string", "UnresolvedSchema_213");
      Resolver.Action resolver_Action0 = Resolver.EnumAdjust.resolve(schema1, schema0, genericData0);
      Resolver.RecordAdjust resolver_RecordAdjust0 = (Resolver.RecordAdjust)Resolver.resolve(resolver_Action0.reader, schema1);
      assertEquals(0, resolver_RecordAdjust0.firstDefault);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("EDUM");
      linkedList0.add("RECORD");
      Schema schema0 = Schema.createEnum("EDUM", "EDUM", "EDUM", (List<String>) linkedList0);
      Resolver.EnumAdjust resolver_EnumAdjust0 = (Resolver.EnumAdjust)Resolver.resolve(schema0, schema0);
      assertTrue(resolver_EnumAdjust0.noAdjustmentsNeeded);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum((String) null, (String) null, (String) null, (List<String>) linkedList0);
      Schema schema1 = Schema.createEnum((String) null, "value", "nw]dx{|'S-a'%6t", (List<String>) linkedList0);
      Resolver.EnumAdjust resolver_EnumAdjust0 = (Resolver.EnumAdjust)Resolver.resolve(schema0, schema1);
      assertTrue(resolver_EnumAdjust0.noAdjustmentsNeeded);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NameValidator nameValidator0 = mock(NameValidator.class, new ViolatedAssumptionAnswer());
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema0 = parseContext0.find("[mq=Z_2", "' (");
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0, genericData0);
      Resolver.ErrorAction.ErrorType resolver_ErrorAction_ErrorType0 = Resolver.ErrorAction.ErrorType.MISSING_REQUIRED_FIELD;
      Resolver.ErrorAction resolver_ErrorAction0 = new Resolver.ErrorAction(resolver_Action0.reader, resolver_Action0.reader, genericData0, resolver_ErrorAction_ErrorType0);
      Conversions.UUIDConversion conversions_UUIDConversion0 = new Conversions.UUIDConversion();
      Schema schema1 = conversions_UUIDConversion0.getRecommendedSchema();
      Resolver.ErrorAction resolver_ErrorAction1 = new Resolver.ErrorAction(schema1, resolver_ErrorAction0.writer, genericData0, resolver_ErrorAction_ErrorType0);
      String string0 = resolver_ErrorAction1.toString();
      //  // Unstable assertion: assertEquals("Found string, expecting org.apache.avro.compiler.UnresolvedSchema_205, missing required field <oops>", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createMap(schema0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema1);
      NameValidator nameValidator0 = mock(NameValidator.class, new ViolatedAssumptionAnswer());
      ParseContext parseContext0 = new ParseContext(nameValidator0);
      Schema schema2 = parseContext0.resolve(resolver_Action0.reader);
      Resolver.Action resolver_Action1 = Resolver.resolve(schema2, schema1);
      assertNotSame(resolver_Action0, resolver_Action1);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Schema schema1 = Schema.createArray(schema0);
      Schema schema2 = Schema.createArray(schema0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema2);
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(resolver_Action0.reader, schema1, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"array\",\"items\":\"string\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      Schema schema1 = conversions_DurationConversion0.getRecommendedSchema();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Schema schema0 = Schema.createFixed((String) null, (String) null, "UnresolvedSchema_10147", 4);
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema1 = conversions_DurationConversion0.getRecommendedSchema();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.NULL;
      Schema schema0 = Schema.create(schema_Type0);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      Schema schema1 = genericData0.induce((Object) null);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      GenericData genericData0 = new GenericData();
      Schema schema0 = Schema.createRecord("EDUM", "UnresolvedSchema_7834", "EDUM", true);
      // Undeclared exception!
      try { 
        Resolver.resolve(schema0, schema0, genericData0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Schema schema0 = Schema.createRecord("EDUM", "EDUM", "EDUM", true);
      // Undeclared exception!
      try { 
        Resolver.resolve(schema0, schema0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Schema fields not set yet
         //
         verifyException("org.apache.avro.Schema$RecordSchema", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      // Undeclared exception!
      try { 
        Resolver.resolve((Schema) null, (Schema) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Protocol.SYSTEM_ERROR;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema1);
      GenericData genericData0 = GenericData.get();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Resolver.ReaderUnion resolver_ReaderUnion0 = (Resolver.ReaderUnion)Resolver.ReaderUnion.resolve(resolver_Action0.reader, schema0, genericData0, hashMap0);
      assertEquals(0, resolver_ReaderUnion0.firstMatch);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
      Schema schema1 = Schema.createArray(schema0);
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Resolver.Action resolver_Action0 = Resolver.ReaderUnion.resolve(schema1, schema0, genericData0, hashMap0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.WriterUnion.resolve(resolver_Action0.reader, resolver_Action0.writer, genericData0, hashMap0);
      assertTrue(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.WriterUnion.resolve(schema1, schema0, genericData0, hashMap0);
      assertFalse(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum((String) null, "Kkv", "Kkv", (List<String>) linkedList0);
      GenericData genericData0 = new GenericData();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0, genericData0);
      Resolver.EnumAdjust resolver_EnumAdjust0 = (Resolver.EnumAdjust)Resolver.EnumAdjust.resolve(resolver_Action0.reader, resolver_Action0.reader, genericData0);
      assertTrue(resolver_EnumAdjust0.noAdjustmentsNeeded);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = new GenericData();
      // Undeclared exception!
      try { 
        Resolver.EnumAdjust.resolve(resolver_Action0.reader, resolver_Action0.reader, genericData0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not an enum: [\"string\"]
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema0 = Schema.create(schema_Type0);
      Conversions.BigDecimalConversion conversions_BigDecimalConversion0 = new Conversions.BigDecimalConversion();
      Schema schema1 = conversions_BigDecimalConversion0.getRecommendedSchema();
      boolean boolean0 = Resolver.Promote.isValid(schema1, schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.INT;
      Schema schema1 = Schema.create(schema_Type1);
      boolean boolean0 = Resolver.Promote.isValid(schema1, schema0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.FLOAT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      boolean boolean0 = Resolver.Promote.isValid(schema1, resolver_Action0.writer);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.INT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      boolean boolean0 = Resolver.Promote.isValid(schema1, resolver_Action0.reader);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      GenericData genericData0 = GenericData.get();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0, genericData0);
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema1 = Schema.createUnion((List<Schema>) linkedList0);
      boolean boolean0 = Resolver.Promote.isValid(schema1, resolver_Action0.writer);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.INT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      boolean boolean0 = Resolver.Promote.isValid(resolver_Action0.writer, resolver_Action0.reader);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      Schema schema1 = Schema.createUnion((List<Schema>) linkedList0);
      boolean boolean0 = Resolver.Promote.isValid(schema0, schema1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      Schema.Type schema_Type0 = Schema.Type.STRING;
      Schema schema1 = Schema.create(schema_Type0);
      boolean boolean0 = Resolver.Promote.isValid(schema0, schema1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Conversions.BigDecimalConversion conversions_BigDecimalConversion0 = new Conversions.BigDecimalConversion();
      Schema schema1 = conversions_BigDecimalConversion0.getRecommendedSchema();
      boolean boolean0 = Resolver.Promote.isValid(schema0, schema1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      GenericData genericData0 = GenericData.get();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0, genericData0);
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema1 = Schema.createUnion((List<Schema>) linkedList0);
      boolean boolean0 = Resolver.Promote.isValid(schema1, resolver_Action0.reader);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema0 = Schema.createUnion((List<Schema>) linkedList0);
      Schema schema1 = Schema.createArray(schema0);
      ClassLoader classLoader0 = ClassLoader.getPlatformClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      Resolver.Action resolver_Action0 = Resolver.Promote.resolve(schema1, schema0, genericData0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(schema0, schema0);
      GenericData genericData0 = new GenericData();
      Resolver.DoNothing resolver_DoNothing0 = new Resolver.DoNothing(resolver_WriterUnion0.writer, resolver_WriterUnion0.reader, genericData0);
      Resolver.Container resolver_Container0 = new Resolver.Container(resolver_DoNothing0.writer, resolver_DoNothing0.writer, genericData0, resolver_WriterUnion0);
      assertTrue(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      GenericData genericData0 = new GenericData();
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(schema0, schema0, genericData0);
      Resolver.ReaderUnion resolver_ReaderUnion0 = new Resolver.ReaderUnion(schema0, schema0, genericData0, 448, resolver_WriterUnion0);
      assertEquals(448, resolver_ReaderUnion0.firstMatch);
      assertTrue(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        Resolver.resolve(schema0, schema0, (GenericData) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema1 = conversions_DurationConversion0.getRecommendedSchema();
      Schema[] schemaArray0 = new Schema[1];
      schemaArray0[0] = schema1;
      Schema schema2 = Schema.createUnion(schemaArray0);
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(schema0, schema2);
      assertFalse(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      LinkedList<Schema> linkedList0 = new LinkedList<Schema>();
      Schema schema1 = Schema.createUnion((List<Schema>) linkedList0);
      Resolver.WriterUnion resolver_WriterUnion0 = (Resolver.WriterUnion)Resolver.resolve(schema1, schema0);
      assertFalse(resolver_WriterUnion0.unionEquiv);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = Schema.createFixed((String) null, (String) null, (String) null, 9);
      Schema schema1 = conversions_DurationConversion0.getRecommendedSchema();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(resolver_Action0.reader, schema1, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"fixed\",\"size\":9}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Schema schema1 = Schema.createArray(schema0);
      GenericData genericData0 = new GenericData();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema1, schema1, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"array\",\"items\":\"float\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"bytes\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      GenericData genericData0 = new GenericData((ClassLoader) null);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"double\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"float\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, (GenericData) null, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"long\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      GenericData genericData0 = new GenericData();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"int\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      GenericData genericData0 = new GenericData();
      Schema schema0 = genericData0.induce((Object) null);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"null\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      GenericData genericData0 = new GenericData();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("avro.java.string", "org.apache.avro.fastread");
      Schema schema1 = parseContext0.find("org.apache.avro.fastread", "org.apache.avro.fastread");
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema1, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"name\":\"UnresolvedSchema_374\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"org.apache.avro.fastread\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      GenericData genericData0 = GenericData.get();
      Schema schema0 = Schema.createFixed("org.apache.avro.fastread", "avro.java.string", "org.apache.avro.fastread", 2355);
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"fixed\",\"name\":\"fastread\",\"namespace\":\"org.apache.avro\",\"doc\":\"avro.java.string\",\"size\":2355}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      GenericData genericData0 = GenericData.get();
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("avro.java.string", "avro.java.string");
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, schema0, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: {\"type\":\"record\",\"name\":\"UnresolvedSchema_375\",\"namespace\":\"org.apache.avro.compiler\",\"doc\":\"unresolved schema\",\"fields\":[],\"org.apache.avro.idl.unresolved.name\":\"avro.java.string\"}
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Schema schema1 = Schema.createArray(schema0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      Schema schema0 = Schema.createEnum("UresovedpSchma_995", "UresovedpSchma_995", "UresovedpSchma_995", (List<String>) linkedList0);
      Schema[] schemaArray0 = new Schema[2];
      schemaArray0[0] = schema0;
      Schema schema1 = Schema.createEnum("avro.java.string", "avro.java.string", "D<C]C[J#Nmn=", (List<String>) linkedList0);
      schemaArray0[1] = schema1;
      Schema schema2 = Schema.createUnion(schemaArray0);
      Resolver.ReaderUnion resolver_ReaderUnion0 = (Resolver.ReaderUnion)Resolver.resolve(schema1, schema2);
      assertEquals(1, resolver_ReaderUnion0.firstMatch);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      Schema[] schemaArray0 = new Schema[1];
      schemaArray0[0] = schema0;
      Schema schema1 = Schema.createUnion(schemaArray0);
      Resolver.ReaderUnion resolver_ReaderUnion0 = (Resolver.ReaderUnion)Resolver.resolve(schema0, schema1);
      assertEquals(0, resolver_ReaderUnion0.firstMatch);
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("7-FZ", "7-FZ");
      Schema[] schemaArray0 = new Schema[1];
      schemaArray0[0] = schema0;
      Schema schema1 = Schema.createUnion(schemaArray0);
      Resolver.ReaderUnion resolver_ReaderUnion0 = (Resolver.ReaderUnion)Resolver.resolve(schema0, schema1);
      assertEquals(0, resolver_ReaderUnion0.firstMatch);
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      GenericData genericData0 = GenericData.get();
      Schema schema0 = parseContext0.find("org.apache.avro.fastread", "UnresolvedSchema_213");
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      Resolver.Action resolver_Action0 = Resolver.RecordAdjust.resolve(schema0, schema0, genericData0, hashMap0);
      Resolver.RecordAdjust resolver_RecordAdjust0 = (Resolver.RecordAdjust)Resolver.RecordAdjust.resolve(resolver_Action0.writer, schema0, genericData0, hashMap0);
      assertEquals(0, resolver_RecordAdjust0.firstDefault);
  }

  @Test(timeout = 4000)
  public void test57()  throws Throwable  {
      ParseContext parseContext0 = new ParseContext();
      Schema schema0 = parseContext0.find("UneolvedShia_23", "UneolvedShia_23");
      Resolver.RecordAdjust resolver_RecordAdjust0 = (Resolver.RecordAdjust)Resolver.resolve(schema0, schema0);
      assertNotNull(resolver_RecordAdjust0);
      
      boolean boolean0 = resolver_RecordAdjust0.noReorder();
      assertTrue(boolean0);
      assertEquals(0, resolver_RecordAdjust0.firstDefault);
  }

  @Test(timeout = 4000)
  public void test58()  throws Throwable  {
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("EDUM");
      Schema schema0 = Schema.createEnum("EDUM", "EDUM", "EDUM", (List<String>) linkedList0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = GenericData.get();
      Resolver.EnumAdjust resolver_EnumAdjust0 = (Resolver.EnumAdjust)Resolver.EnumAdjust.resolve(schema0, resolver_Action0.writer, genericData0);
      assertTrue(resolver_EnumAdjust0.noAdjustmentsNeeded);
  }

  @Test(timeout = 4000)
  public void test59()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.ReaderUnion resolver_ReaderUnion0 = (Resolver.ReaderUnion)Resolver.resolve(schema0, schema1);
      assertEquals(0, resolver_ReaderUnion0.firstMatch);
  }

  @Test(timeout = 4000)
  public void test60()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.FLOAT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      boolean boolean0 = Resolver.Promote.isValid(schema0, resolver_Action0.writer);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test61()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.DOUBLE;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.LONG;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      GenericData genericData0 = GenericData.get();
      Resolver.Action resolver_Action1 = Resolver.resolve(resolver_Action0.reader, resolver_Action0.reader, genericData0);
      boolean boolean0 = Resolver.Promote.isValid(schema1, resolver_Action1.reader);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test62()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.FLOAT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      boolean boolean0 = Resolver.Promote.isValid(resolver_Action0.writer, resolver_Action0.reader);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test63()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema.Type schema_Type1 = Schema.Type.FLOAT;
      Schema schema1 = Schema.create(schema_Type1);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      ClassLoader classLoader0 = ClassLoader.getSystemClassLoader();
      GenericData genericData0 = new GenericData(classLoader0);
      Resolver.Action resolver_Action1 = Resolver.Promote.resolve(resolver_Action0.writer, resolver_Action0.reader, genericData0);
      assertFalse(resolver_Action1.equals((Object)resolver_Action0));
  }

  @Test(timeout = 4000)
  public void test64()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      // Undeclared exception!
      try { 
        Resolver.Promote.isValid(schema0, schema0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Only use when reader and writer are different.
         //
         verifyException("org.apache.avro.Resolver$Promote", e);
      }
  }

  @Test(timeout = 4000)
  public void test65()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      String string0 = ((Resolver.ErrorAction) resolver_Action0).toString();
      assertEquals("Found int, expecting union[string]", string0);
  }

  @Test(timeout = 4000)
  public void test66()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      GenericData genericData0 = new GenericData();
      Resolver.ErrorAction.ErrorType resolver_ErrorAction_ErrorType0 = Resolver.ErrorAction.ErrorType.SIZES_DONT_MATCH;
      Resolver.ErrorAction resolver_ErrorAction0 = new Resolver.ErrorAction(schema0, schema0, genericData0, resolver_ErrorAction_ErrorType0);
      String string0 = resolver_ErrorAction0.toString();
      assertEquals("Found time.Duration, expecting time.Duration", string0);
  }

  @Test(timeout = 4000)
  public void test67()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERROR;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = new GenericData();
      Resolver.ErrorAction.ErrorType resolver_ErrorAction_ErrorType0 = Resolver.ErrorAction.ErrorType.NAMES_DONT_MATCH;
      Resolver.ErrorAction resolver_ErrorAction0 = new Resolver.ErrorAction(resolver_Action0.reader, resolver_Action0.reader, genericData0, resolver_ErrorAction_ErrorType0);
      String string0 = resolver_ErrorAction0.toString();
      assertEquals("Found string, expecting string", string0);
  }

  @Test(timeout = 4000)
  public void test68()  throws Throwable  {
      GenericData genericData0 = GenericData.get();
      Resolver.ErrorAction.ErrorType resolver_ErrorAction_ErrorType0 = Resolver.ErrorAction.ErrorType.MISSING_REQUIRED_FIELD;
      Resolver.ErrorAction resolver_ErrorAction0 = new Resolver.ErrorAction((Schema) null, (Schema) null, genericData0, resolver_ErrorAction_ErrorType0);
      // Undeclared exception!
      try { 
        resolver_ErrorAction0.toString();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.avro.Resolver$ErrorAction", e);
      }
  }

  @Test(timeout = 4000)
  public void test69()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.LONG;
      Schema schema0 = Schema.create(schema_Type0);
      Schema schema1 = Protocol.SYSTEM_ERROR;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema1, schema0);
      String string0 = ((Resolver.ErrorAction) resolver_Action0).toString();
      assertEquals("Found string, expecting long", string0);
  }

  @Test(timeout = 4000)
  public void test70()  throws Throwable  {
      Schema schema0 = Schema.createFixed("Duration", "Duration", "Duration", 1761);
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema1 = conversions_DurationConversion0.getRecommendedSchema();
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema1);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test71()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BYTES;
      Schema schema0 = Schema.create(schema_Type0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test72()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.FLOAT;
      Schema schema0 = Schema.create(schema_Type0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test73()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.INT;
      Schema schema0 = Schema.create(schema_Type0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      assertNotNull(resolver_Action0);
  }

  @Test(timeout = 4000)
  public void test74()  throws Throwable  {
      Schema.Type schema_Type0 = Schema.Type.BOOLEAN;
      Schema schema0 = Schema.create(schema_Type0);
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = new GenericData();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.WriterUnion.resolve(schema0, resolver_Action0.reader, genericData0, hashMap0);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Not a union: \"boolean\"
         //
         verifyException("org.apache.avro.Schema", e);
      }
  }

  @Test(timeout = 4000)
  public void test75()  throws Throwable  {
      Schema schema0 = Protocol.SYSTEM_ERRORS;
      Resolver.Action resolver_Action0 = Resolver.resolve(schema0, schema0);
      GenericData genericData0 = GenericData.get();
      HashMap<Schema.SeenPair, Resolver.Action> hashMap0 = new HashMap<Schema.SeenPair, Resolver.Action>();
      // Undeclared exception!
      try { 
        Resolver.ReaderUnion.resolve(resolver_Action0.writer, schema0, genericData0, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Writer schema is union.
         //
         verifyException("org.apache.avro.Resolver$ReaderUnion", e);
      }
  }

  @Test(timeout = 4000)
  public void test76()  throws Throwable  {
      Conversions.DurationConversion conversions_DurationConversion0 = new Conversions.DurationConversion();
      Schema schema0 = conversions_DurationConversion0.getRecommendedSchema();
      GenericData genericData0 = new GenericData();
      Resolver.Skip resolver_Skip0 = new Resolver.Skip(schema0, genericData0);
  }

  @Test(timeout = 4000)
  public void test77()  throws Throwable  {
      Resolver resolver0 = new Resolver();
  }
}
