name: SonarCloud

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          cd lang/java
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=lucaaa02_avro \
            -Dsonar.organization=lucaaa02 \
            -Dsonar.host.url=https://sonarcloud.io
